-- ============================================================
-- TEMA N°1: SQL DML Y SQL DDL EN ORACLE DATABASE
-- Autor: Marquinhos Benites
-- Descripción: Script completo con creación, inserción, consultas
--              y mantenimiento de tablas con restricciones.
-- ============================================================

-- ============================================================
-- 🧱 BLOQUE 1: CREACIÓN DE TABLAS (DDL)
-- ============================================================

-- ========================
-- TABLA EMPLEADOS
-- ========================
CREATE TABLE EMPLEADOS (
    DNI            NUMBER(10) PRIMARY KEY,
    NOMBRE         VARCHAR2(30),
    APELLIDO1      VARCHAR2(30) NOT NULL,
    APELLIDO2      VARCHAR2(30),
    SEXO           CHAR(1) CHECK (SEXO IN ('H','M')),
    TELEFONO       VARCHAR2(15),
    CELULAR        VARCHAR2(15),
    CIUDAD         VARCHAR2(30),
    COD_POSTAL     VARCHAR2(10),
    FECHA_NAC      DATE,
    VALORACION     NUMBER(2) DEFAULT 5 CHECK (VALORACION BETWEEN 1 AND 10),
    CONSTRAINT CK_CIUDAD_CODPOSTAL CHECK ((CIUDAD IS NULL) OR (COD_POSTAL IS NOT NULL))
);

-- ========================
-- TABLA DEPARTAMENTOS
-- ========================
CREATE TABLE DEPARTAMENTOS (
    DPTO_COD     NUMBER(5) PRIMARY KEY,
    NOMBRE_DPTO  VARCHAR2(50) UNIQUE NOT NULL,
    PRESUPUESTO  NUMBER(10,2) NOT NULL
);

-- ========================
-- TABLA TRABAJOS
-- ========================
CREATE TABLE TRABAJOS (
    TRABAJO_COD   NUMBER(5) PRIMARY KEY,
    NOMBRE_TRAB   VARCHAR2(50) UNIQUE NOT NULL,
    SALARIO_MIN   NUMBER(10,2) NOT NULL,
    SALARIO_MAX   NUMBER(10,2) NOT NULL,
    CONSTRAINT CK_SALARIO CHECK (SALARIO_MIN < SALARIO_MAX)
);

-- ========================
-- TABLA HISTORIAL LABORAL
-- ========================
CREATE TABLE HISTORIAL_LABORAL (
    EMPLEADO_DNI   NUMBER(10),
    TRABAJO_COD    NUMBER(5),
    FECHA_INICIO   DATE NOT NULL,
    DPTO_COD       NUMBER(5),
    SUPERVISOR_DNI NUMBER(10),
    CONSTRAINT PK_HISTLAB PRIMARY KEY (EMPLEADO_DNI, FECHA_INICIO),
    CONSTRAINT FK_HL_EMP FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI),
    CONSTRAINT FK_HL_TRAB FOREIGN KEY (TRABAJO_COD) REFERENCES TRABAJOS(TRABAJO_COD),
    CONSTRAINT FK_HL_DPTO FOREIGN KEY (DPTO_COD) REFERENCES DEPARTAMENTOS(DPTO_COD),
    CONSTRAINT FK_HL_SUP FOREIGN KEY (SUPERVISOR_DNI) REFERENCES EMPLEADOS(DNI)
);

-- ========================
-- TABLA HISTORIAL SALARIAL
-- ========================
CREATE TABLE HISTORIAL_SALARIAL (
    EMPLEADO_DNI   NUMBER(10),
    SALARIO        NUMBER(10,2) NOT NULL,
    FECHA_COMIENZO DATE NOT NULL,
    FECHA_FIN      DATE,
    CONSTRAINT PK_HISTSAL PRIMARY KEY (EMPLEADO_DNI, FECHA_COMIENZO),
    CONSTRAINT FK_HS_EMP FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI)
);

-- ========================
-- TABLA UNIVERSIDADES
-- ========================
CREATE TABLE UNIVERSIDADES (
    UNIV_COD     NUMBER(5) PRIMARY KEY,
    NOMBRE_UNIV  VARCHAR2(100) UNIQUE NOT NULL,
    CIUDAD       VARCHAR2(50)
);

-- ========================
-- TABLA ESTUDIOS
-- ========================
CREATE TABLE ESTUDIOS (
    EMPLEADO_DNI NUMBER(10),
    UNIVERSIDAD  NUMBER(5),
    ANIO         NUMBER(4),
    GRADO        VARCHAR2(20),
    ESPECIALIDAD VARCHAR2(50),
    CONSTRAINT PK_ESTUDIOS PRIMARY KEY (EMPLEADO_DNI, UNIVERSIDAD),
    CONSTRAINT FK_EST_EMP FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI),
    CONSTRAINT FK_EST_UNIV FOREIGN KEY (UNIVERSIDAD) REFERENCES UNIVERSIDADES(UNIV_COD) ON DELETE CASCADE
);

-- ============================================================
-- 🧩 BLOQUE 2: INSERCIÓN DE DATOS (DML)
-- ============================================================

-- EMPLEADOS
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO1, APELLIDO2, DNI, SEXO, TELEFONO, CELULAR, CIUDAD, COD_POSTAL, FECHA_NAC)
VALUES ('Sergio', 'Palma', 'Entrena', 111222, 'H', '4567890', '987654321', 'Lima', '15001', TO_DATE('15/05/1985','DD/MM/YYYY'));

INSERT INTO EMPLEADOS (NOMBRE, APELLIDO1, APELLIDO2, DNI, SEXO, TELEFONO, CELULAR, CIUDAD, COD_POSTAL, FECHA_NAC)
VALUES ('Lucia', 'Ortega', 'Plus', 222333, 'M', '1234567', '912345678', 'Cusco', '08002', TO_DATE('20/10/1990','DD/MM/YYYY'));

INSERT INTO EMPLEADOS (NOMBRE, APELLIDO1, APELLIDO2, DNI, SEXO, TELEFONO, CELULAR, CIUDAD, COD_POSTAL, FECHA_NAC)
VALUES ('Carlos', 'Lopez', 'Ruiz', 333444, 'H', '7654321', '911223344', 'Málaga', '29001', TO_DATE('01/03/1992','DD/MM/YYYY'));

-- DEPARTAMENTOS
INSERT INTO DEPARTAMENTOS (DPTO_COD, NOMBRE_DPTO, PRESUPUESTO) VALUES (10, 'Contabilidad', 50000);
INSERT INTO DEPARTAMENTOS (DPTO_COD, NOMBRE_DPTO, PRESUPUESTO) VALUES (20, 'Recursos Humanos', 30000);

-- TRABAJOS
INSERT INTO TRABAJOS (TRABAJO_COD, NOMBRE_TRAB, SALARIO_MIN, SALARIO_MAX) VALUES (101, 'Analista', 1000, 3000);
INSERT INTO TRABAJOS (TRABAJO_COD, NOMBRE_TRAB, SALARIO_MIN, SALARIO_MAX) VALUES (102, 'Programador', 1200, 4000);

-- HISTORIAL LABORAL
INSERT INTO HISTORIAL_LABORAL (EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO, DPTO_COD, SUPERVISOR_DNI)
VALUES (111222, 101, TO_DATE('16/06/1996','DD/MM/YYYY'), 20, 222333);

-- HISTORIAL SALARIAL
INSERT INTO HISTORIAL_SALARIAL (EMPLEADO_DNI, SALARIO, FECHA_COMIENZO)
VALUES (111222, 2500, TO_DATE('01/01/2020','DD/MM/YYYY'));
INSERT INTO HISTORIAL_SALARIAL (EMPLEADO_DNI, SALARIO, FECHA_COMIENZO)
VALUES (222333, 3000, TO_DATE('01/01/2021','DD/MM/YYYY'));
INSERT INTO HISTORIAL_SALARIAL (EMPLEADO_DNI, SALARIO, FECHA_COMIENZO)
VALUES (333444, 2800, TO_DATE('01/01/2022','DD/MM/YYYY'));

-- UNIVERSIDADES
INSERT INTO UNIVERSIDADES (UNIV_COD, NOMBRE_UNIV, CIUDAD) VALUES (1, 'San Marcos', 'Lima');
INSERT INTO UNIVERSIDADES (UNIV_COD, NOMBRE_UNIV, CIUDAD) VALUES (2, 'PUCP', 'Lima');

-- ESTUDIOS
INSERT INTO ESTUDIOS (EMPLEADO_DNI, UNIVERSIDAD, ANIO, GRADO, ESPECIALIDAD)
VALUES (111222, 1, 2010, 'Lic', 'Contabilidad');
INSERT INTO ESTUDIOS (EMPLEADO_DNI, UNIVERSIDAD, ANIO, GRADO, ESPECIALIDAD)
VALUES (222333, 2, 2015, 'Ing', 'Sistemas');
INSERT INTO ESTUDIOS (EMPLEADO_DNI, UNIVERSIDAD, ANIO, GRADO, ESPECIALIDAD)
VALUES (333444, 1, 2014, 'Lic', 'Administración');

-- ============================================================
-- ⚙️ BLOQUE 3: CONSULTAS (SELECT, UPDATE, DELETE)
-- ============================================================

-- CONSULTAS BÁSICAS
SELECT * FROM EMPLEADOS;
SELECT NOMBRE, APELLIDO1, CIUDAD FROM EMPLEADOS WHERE SEXO = 'M';

-- CONSULTAS COMPLETAS CON JOIN
SELECT E.NOMBRE, E.APELLIDO1, D.NOMBRE_DPTO, T.NOMBRE_TRAB
FROM EMPLEADOS E
JOIN HISTORIAL_LABORAL H ON E.DNI = H.EMPLEADO_DNI
JOIN DEPARTAMENTOS D ON H.DPTO_COD = D.DPTO_COD
JOIN TRABAJOS T ON H.TRABAJO_COD = T.TRABAJO_COD;

-- ACTUALIZACIÓN DE DATOS
UPDATE HISTORIAL_SALARIAL SET SALARIO = SALARIO * 1.1 WHERE EMPLEADO_DNI = 111222;

-- ELIMINACIÓN DE REGISTROS
DELETE FROM HISTORIAL_SALARIAL WHERE FECHA_COMIENZO < TO_DATE('01/01/2020','DD/MM/YYYY');

-- ============================================================
-- 🧩 BLOQUE 4: ALTERACIONES DE ESTRUCTURA (ALTER TABLE)
-- ============================================================

ALTER TABLE EMPLEADOS ADD (EMAIL VARCHAR2(50));
ALTER TABLE DEPARTAMENTOS MODIFY (PRESUPUESTO NUMBER(12,2));
ALTER TABLE TRABAJOS DROP COLUMN SALARIO_MAX;

-- ============================================================
-- 🧩 BLOQUE 5: CREACIÓN DE VISTAS (VIEW)
-- ============================================================

CREATE VIEW VW_EMPLEADOS_LIMA AS
SELECT NOMBRE, APELLIDO1, CIUDAD FROM EMPLEADOS WHERE CIUDAD = 'Lima';

CREATE VIEW VW_HISTORIAL_COMPLETO AS
SELECT E.NOMBRE, T.NOMBRE_TRAB, D.NOMBRE_DPTO, H.FECHA_INICIO
FROM EMPLEADOS E
JOIN HISTORIAL_LABORAL H ON E.DNI = H.EMPLEADO_DNI
JOIN TRABAJOS T ON H.TRABAJO_COD = T.TRABAJO_COD
JOIN DEPARTAMENTOS D ON H.DPTO_COD = D.DPTO_COD;

CREATE VIEW VW_SALARIOS_MAYORES_2500 AS
SELECT E.NOMBRE, S.SALARIO FROM EMPLEADOS E
JOIN HISTORIAL_SALARIAL S ON E.DNI = S.EMPLEADO_DNI
WHERE S.SALARIO > 2500;

-- ============================================================
-- 🧩 BLOQUE 6: ELIMINACIÓN DE TABLAS (DROP TABLE)
-- ============================================================

DROP TABLE ESTUDIOS CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL_SALARIAL CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL_LABORAL CASCADE CONSTRAINTS;
DROP TABLE TRABAJOS CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS;
DROP TABLE UNIVERSIDADES CASCADE CONSTRAINTS;
DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;

-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================
